const types = {
  SET_INITIAL_BUDGET: 'SET_INITIAL_BUDGET',
  REMOVE_INITIAL_BUDGET: 'REMOVE_INITIAL_BUDGET',
  ADD_EXPENDITURE: 'ADD_EXPENDITURE',
  DELETE_EXPENDITURE: 'DELETE_EXPENDITURE',
  SET_EDIT_EXPENDITURE: 'SET_EDIT_EXPENDITURE',
  RESET_EDIT_EXPENDITURE: 'RESET_EDIT_EXPENDITURE',
  EDIT_EXPENDITURE: 'EDIT_EXPENDITURE',
  FILTERED_EXPENDITURE: 'FILTERED_EXPENDITURE',
  TOTAL_EXPENDITURE: 'TOTAL_EXPENDITURE',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
};

export default types;
